version: '3'
services:
  api:
    build: ./api
    ports:
      - '3002:3002'
    environment:
      PORT: 3002
      DATABASE_URL: postgresql://postgres:postgres@db:5432/blog_db
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - blog-network

  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - blog-network

  db:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blog-network

volumes:
  postgres_data:

networks:
  blog-network:
    driver: bridge
